% This script is written and read by pdetool and should NOT be edited.
% There are two recommended alternatives:
 % 1) Export the required variables from pdetool and create a MATLAB script
 %    to perform operations on these.
 % 2) Define the problem completely using a MATLAB script. See
 %    http://www.mathworks.com/help/pde/examples/index.html for examples
 %    of this approach.
function pdemodel
[pde_fig,ax]=pdeinit;
pdetool('appl_cb',5);
pdetool('snapon','on');
set(ax,'DataAspectRatio',[1 0.1875 1]);
set(ax,'PlotBoxAspectRatio',[200 133.33333333333334 1]);
set(ax,'XLim',[-200 200]);
set(ax,'YLim',[0 50]);
set(ax,'XTick',[ -1000,...
 1000,...
]);
set(ax,'YTick',[ 0,...
 1000,...
]);
pdetool('gridon','on');

% Geometry description:
pdecirc(0,20,5,'C1');
pderect([-5 5 1000 20],'R1');
pdepoly([ -700,...
 700,...
 5,...
 -5,...
],...
[ 1000,...
 1000,...
 19.5,...
 19.5,...
],...
 'P1');
pderect([-1000 1000 1000 0],'R2');
set(findobj(get(pde_fig,'Children'),'Tag','PDEEval'),'String','R2-(C1+R1+P1)')

% Boundary conditions:
pdetool('changemode',0)
pdesetbd(11,...
'dir',...
1,...
'1',...
'0.5')
pdesetbd(10,...
'dir',...
1,...
'1',...
'0.5')
pdesetbd(9,...
'dir',...
1,...
'1',...
'0')
pdesetbd(8,...
'dir',...
1,...
'1',...
'0')
pdesetbd(7,...
'neu',...
1,...
'0',...
'0')
pdesetbd(6,...
'neu',...
1,...
'0',...
'0')
pdesetbd(5,...
'neu',...
1,...
'0',...
'0')
pdesetbd(4,...
'dir',...
1,...
'1',...
'0')
pdesetbd(3,...
'neu',...
1,...
'0',...
'0')
pdesetbd(2,...
'dir',...
1,...
'1',...
'0.5')
pdesetbd(1,...
'dir',...
1,...
'1',...
'0.5')

% Mesh generation:
setappdata(pde_fig,'Hgrad',1.3);
setappdata(pde_fig,'refinemethod','regular');
setappdata(pde_fig,'jiggle',char('on','mean',''));
setappdata(pde_fig,'MesherVersion','R2013a');
pdetool('initmesh')
pdetool('refine')
pdetool('refine')
pdetool('refine')
pdetool('jiggle')

% PDE coefficients:
pdeseteq(1,...
'1.0',...
'0.0',...
'0',...
'1.0',...
'0:10',...
'0.0',...
'0.0',...
'[0 100]')
setappdata(pde_fig,'currparam',...
['1.0';...
'0  '])

% Solve parameters:
setappdata(pde_fig,'solveparam',...
char('0','134784','10','pdeadworst',...
'0.5','longest','0','1e-4','','fixed','inf'))

% Plotflags and user data strings:
setappdata(pde_fig,'plotflags',[2 2 1 1 1 1 7 1 0 0 0 1 1 0 0 1 0 1]);
setappdata(pde_fig,'colstring','');
setappdata(pde_fig,'arrowstring','');
setappdata(pde_fig,'deformstring','');
setappdata(pde_fig,'heightstring','');

% Solve PDE:
pdetool('solve')
